# Generated by Django 3.1.6 on 2021-03-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_shoppinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='meals',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.Recipe'),
        ),
    ]
