# Generated by Django 3.1.6 on 2021-03-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210303_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='food_type',
            field=models.CharField(choices=[('VG', 'Vegetable'), ('FR', 'Fruit'), ('MT', 'Meat'), ('D', 'Dairy'), ('O', 'Other')], default='O', max_length=2, null=True),
        ),
    ]
